### ISSUE TITLE
Incredibly Slow and Stuck for hours

### ISSUE THREAD

**Issue by Varusal** [nickrussler/email-to-pdf-converter#30]
I'm currently in the progress of converting 5005 *.eml files but as it turns out, the tool is incredibly slow and gets stuck very often.
This goes for both, the GUI and the *.jar file (cmd).

As you can see in the image, it only converted 519 files (started at 7am in the morning). The current processed file is in progress for about an hour.
![image](https://user-images.githubusercontent.com/10616926/103484013-b688bd00-4deb-11eb-9c6a-8a4a95f36f98.png)

Any idea why it takes that long to process files?

**Comment by nickrussler** [comment]
Can you check if older versions are faster? This one in particular: https://github.com/nickrussler/email-to-pdf-converter/releases/tag/2.2.2

**Comment by Varusal** [comment]
> Can you check if older versions are faster? This one in particular: https://github.com/nickrussler/email-to-pdf-converter/releases/tag/2.2.2

I'm currently testing it. So far 70 files got converted in under 5 Minutes.
I will report back as soon the conversion is done or an issues occurs.

**Comment by Varusal** [comment]
No luck. Now it got stuck at 72.

**Comment by nickrussler** [comment]
If you could share a portion of those emails I could look into it when I find some time:
nick.russler@gmail.com

**Comment by Varusal** [comment]
> If you could share a portion of those emails I could look into it when I find some time:
> [nick.russler@gmail.com](mailto:nick.russler@gmail.com)

Thanks but that is currently not possible because they are confidential. I will look through these mails and see if I can find a bunch that are not confidential.
