### ISSUE TITLE
Q: how to use converter from JAVA project?

### ISSUE THREAD

**Issue by kerkhc** [nickrussler/email-to-pdf-converter#31]
Hi Nick,
is it possible to use your converter directly from another JAVA project (some API calls?)

Best regards,
Carsten

**Comment by nickrussler** [comment]
You can call [MimeMessageConverter.convertToPdf](https://github.com/nickrussler/email-to-pdf-converter/blob/master/src/main/java/cli/Main.java#L123) or even the main method directly. Be aware that [several system properties](https://github.com/nickrussler/email-to-pdf-converter/blob/master/src/main/java/mimeparser/MimeMessageConverter.java#L58) are set to change the mime decoding.
