### ISSUE TITLE
Feature Request: option to customize header

### ISSUE THREAD

**Issue by hldrm** [nickrussler/email-to-pdf-converter#38]
it would be nice to add a command line option to customize the header (the text box showing from, to, subject, date, time).
In particular, I am looking for the CC field, BCC – but there is more one can imagine.

Suggestion:
cmd option: 
`-h "BCC,CC"`
this would add the lines CC and BCC to the header text box.

**Comment by nickrussler** [comment]
I'd merge a well written PR for this, but I will not implement it myself.
