### ISSUE TITLE
Problem with greek characters

### ISSUE THREAD

**Issue by mariosvasiliou** [nickrussler/email-to-pdf-converter#39]
Hello, thank you for the great app.
I have an issue with greek characters only with .msg files, .eml files look ok even with greek but on msg files text is not looking OK.
I have tried both Unicode and non-unicode msg files but the same result.
I believe the problem is when exporting to HTML, I have checked HTML and it doesn't look OK.
If I use another program to export the msg files to HTML it looks ok, so I believe something goes wrong when you export to HTML and the text is not encoded correctly.
I forgot to mention that the header part even if the subject is in greek it looks OK.
Thanks

**Comment by nickrussler** [comment]
Please attach one of these problematic msg files
