### ISSUE TITLE
wkhtmltopdf no longer available on some linux systems

### ISSUE THREAD

**Issue by ernstblecha** [nickrussler/email-to-pdf-converter#40]
As Gentoo has dropped support for qtwebkit and wkhtmltopdf (see https://bugs.gentoo.org/684580 and https://bugs.gentoo.org/692532 ) i had to find a replacement. I decided to go the simple route and just write a small bash-script that does what i needed (no support for setting the page size or setting a proxy-server)

```
#!/bin/bash
google-chrome-stable --headless --disable-gpu --incognito --print-to-pdf="${@:(-1)}" "${@:(-2):1}"
```

**Comment by nickrussler** [comment]
I think support for chrome headless or chrome debugging API would be a good path forward. Sadly, few options are supported by headless.

**Comment by JanUlrichR** [comment]
Hey, 
I would like to help you out on this one and have already implemented everything to enable the html -> pdf generation using chrome. However, I am not able to create a branch for a PR. (Maybe I forget something)

Please let me know if you are interested.
