### ISSUE TITLE
Merge header without javascript

### ISSUE THREAD

**Issue by THausherr** [nickrussler/email-to-pdf-converter#43]
This tool really works nicely, but it relies on wkhtmltopdf  having to interprete javascript which is obviously dangerous. I'm wondering whether it would be possible to load, manipulate and save the HTML in java to include the header fields table, which is currently done by the small script attached to the end of the HTML file. Or is this impossible because of the height?

**Comment by nickrussler** [comment]
Would love to ditch the JS, but would require an alternative solution regarding the height yes.
