### ISSUE TITLE
Creation of empty attachment folders

### ISSUE THREAD

**Issue by SarveshBajaj** [nickrussler/email-to-pdf-converter#45]
I had multiple eml files, some having attachments, some not, using the GUI, and ticking the Extract Attachments checkbox resulted in all eml files having a folder created (even though the folders are empty in case of emails with no attachments)
Would like to know if we can check before creating the directory because creation of these empty directories serve no purpose.

In case it is an issue, would work on it.

**Comment by jimspoon** [comment]
If you use the command-line interface you can specify an existing directory to receive the attachments.  In this case new empty directories aren't created.  But if you don't specify this option, all the empty directories will be created, with the same name as the EML file.   I've been removing them using https://github.com/hxseven/Remove-Empty-Directories - works very well.

**Comment by nickrussler** [comment]
@SarveshBajaj "In case it is an issue, would work on it." Yes, I agree, not creating the folders gives better UX. Please feel free to open a PR.

**Comment by SarveshBajaj** [comment]
https://github.com/nickrussler/email-to-pdf-converter/pull/65 - lmk if all's good, tested with all UTs
