### ISSUE TITLE
Store pdf files in a new folder

### ISSUE THREAD

**Issue by SarveshBajaj** [nickrussler/email-to-pdf-converter#46]
Feature option : To give an option to users to store the pdf files in a separate folder.
Currently its stored in the same folder and becomes hard to arrange for multiple files.

Would like to work on the same.

**Comment by jimspoon** [comment]
If you run from the command-line you can use the -o option:
    -o, --output-filepath
      Filepath of the produced PDF document. If this option is omitted the PDF
      will be placed alongside the email File.
