### ISSUE TITLE
Fails to build - A problem occurred starting process 'command 'launch4jc''

### ISSUE THREAD

**Issue by rogard** [nickrussler/email-to-pdf-converter#47]
I get a fail at step 2:

```
gradlew shadowJar
```
https://scans.gradle.com/s/sc2a7tvd6dz7m
```
gradlew dist
```
https://gradle.com/s/dl2g3s572yz2s

Operating System: Linux Mint 19
Kernel: Linux 4.15.0-20-generic
Architecture: x86-64
wkhtmltopdf 0.12.4

**Comment by nickrussler** [comment]
gradlew dist
Same as gradlew shadowJar but additionally creates windows exe launchers in build/libs for gui and console mode. This task needs the [Launch4j](http://launch4j.sourceforge.net/) binary in the PATH.

**Comment by hellogeekzz** [comment]
> gradlew dist Same as gradlew shadowJar but additionally creates windows exe launchers in build/libs for gui and console mode. This task needs the [Launch4j](http://launch4j.sourceforge.net/) binary in the PATH.

![image](https://github.com/nickrussler/email-to-pdf-converter/assets/74523733/1b37d557-2a28-4c27-9082-3a08a6f320e5)
![image](https://github.com/nickrussler/email-to-pdf-converter/assets/74523733/2b99bd4a-cb5d-4f3d-882b-c0aa5579f258)

tried upgrading to 1.8 also can't progress further..
