### ISSUE TITLE
Fail if attachment name contains slash

### ISSUE THREAD

**Issue by dominicraf** [nickrussler/email-to-pdf-converter#48]
Running under Linux with -a option, if the name of an attachment to an email contains a directory-divider character (/) it fails with an error message (but no error code) 'Could not save attachment to ...'

I guess it needs to sanitise filenames before attempting to save them.

Otherwise, very cool indeed - thanks for your work.

**Comment by nickrussler** [comment]
This has been fixed, please check any version >= 2.7.0
