### ISSUE TITLE
please add header attachments.name in the PDF file

### ISSUE THREAD

**Issue by JeffreyBunschoten** [nickrussler/email-to-pdf-converter#51]
I would like to request a feature which also includes the names of all the attachments in the blocked header in the PDF after parsing.
Preferably between the Subject and To fields

Perhaps also with an extra optional button from the GUI to include attachment names or not.

**Comment by nickrussler** [comment]
Fixed in https://github.com/nickrussler/email-to-pdf-converter/pull/63
