### ISSUE TITLE
konverting Email with Attachment in Pdf with Attachment

### ISSUE THREAD

**Issue by pe4000** [nickrussler/email-to-pdf-converter#68]
(1) is it possible to convert an email with an attachment (for example jpg, doc)
 into a pdf so that the email attachment is in the attachment (for example jpg, doc) of the pdf?
(2) Is it possible to start this process from Thunderbird?

**Comment by nickrussler** [comment]
Both are out of scope for this project.vi'd recommend to look into tools to merge these attachments in the PDFs this tool can produce.

**Comment by pe4000** [comment]
Thank you for your fast answer!
