### ISSUE TITLE
Attachments not extracted under Linux for >=2.8.0

### ISSUE THREAD

**Issue by dominicraf** [nickrussler/email-to-pdf-converter#72]
Running under Linux, versions 2.8.0 to 2.10.0 do not extract attachments with -a option. I am guessing this is some unintended side-effect of the new attachment-name-sanitising code. The error message is:
```
The email could not be converted. Error: java.lang.IllegalStateException: Failed to create attachment directory
        at mimeparser.MimeMessageConverter.convertToPdf(MimeMessageConverter.java:363)
        at cli.Main.main(Main.java:126)

```
Version 2.7.0 works as expected.

**Comment by nickrussler** [comment]
Hi, can you please confirm that it works again with this fix:

https://github.com/nickrussler/email-to-pdf-converter/actions/runs/9506992884/artifacts/1599926478

**Comment by dominicraf** [comment]
Yes thanks, that seems to work now, though I have not tested it extensively. Output is:
```
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J(W): Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J(W): Ignoring binding found at [jar:file:/scripts/emailconverter-2.10.0-all.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J(W): See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.

```

**Comment by nickrussler** [comment]
Thanks for the feedback, fix released in https://github.com/nickrussler/email-to-pdf-converter/releases/tag/2.10.1
