### ISSUE TITLE
weird characters when converted on docker

### ISSUE THREAD

**Issue by kshitizwagle** [nickrussler/email-to-pdf-converter#76]
Hi,
I'm using this service, inside a docker container, am good with the conversion but instead of `&nbsp` (html space character) (is totally my guess), am getting this weird character `Â`
It works fine on my WSL but has issues while in docker container, my assumption is that it is something to do with fonts?

Posting images with difference on WSL and docker

![image](https://github.com/nickrussler/email-to-pdf-converter/assets/109206856/4e19ed35-46a7-4cbc-b6c9-16dcac96183a)
![image](https://github.com/nickrussler/email-to-pdf-converter/assets/109206856/cdaef31e-c6f7-4377-8ed0-bc4385412d61)

Any help would be appreciated

**Comment by nickrussler** [comment]
I'd guess it's either fonts or some default encoding is wrong.

Here some chatgpt guidance:

1. **Check Docker Container Locale Settings:**
   Ensure that the locale settings in your Docker container are set correctly. You can check this by running `locale` inside your Docker container. If the locale is not set correctly, you can set it by adding the following lines to your Dockerfile:

   ```Dockerfile
   RUN apt-get update && apt-get install -y locales
   RUN locale-gen en_US.UTF-8
   ENV LANG en_US.UTF-8
   ENV LANGUAGE en_US:en
   ENV LC_ALL en_US.UTF-8
   ```

2. **Verify Fonts Installed in Docker Container:**
   Make sure the necessary fonts are installed in your Docker container. You can install common fonts using:

   ```Dockerfile
   RUN apt-get update && apt-get install -y fonts-dejavu
   ```

   You might need to install additional fonts based on your requirements.

3. **Use Docker's Environment Variable for Java Encoding:**
   Set the environment variable in your Dockerfile to ensure Java uses the correct encoding:

   ```Dockerfile
   ENV JAVA_TOOL_OPTIONS "-Dfile.encoding=UTF-8"
   ```

**Comment by kshitizwagle** [comment]
thanks, i tried a bunch of things, ended up replacing NBSP from the code itself, it ain't elegant but it works right now, will do few experiments!
